matrix:
  include:
    - os: osx
      osx_image: xcode9
      language: objective-c
      sudo: required
    - os: osx
      osx_image: xcode8.3
      language: objective-c
      sudo: required
notifications:
  email: false
branches:
  only:
  - master
before_install:
  - gem install rake
  - gem install fastlane --no-ri --no-rdoc --no-document
jobs:
  include:
    - stage: XCTest
  script:
    - fastlane test
