language: objective-c
osx_image:
- xcode9
- xcode8.3
notifications:
email: false
branches:
only:
- master
before_install:
- gem install fastlane --no-ri --no-rdoc --no-document
script:
- fastlane test
