# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.69.2"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    #cocoapods
    # cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan(
      workspace: "ifaker.xcworkspace",
      scheme: "ifakerTests",
      output_directory: "test_output/",
      clean: true,
      code_coverage: true,
      device: "iPhone 8 Plus",\
  )
  xcov(
    workspace: "ifaker.xcworkspace",
    html_report: true,
    scheme: "ifakerTests",
    output_directory: "xcov_output"
  )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://docs.fastlane.tools/advanced/#control-configuration-by-lane-and-by-platform
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics
